git:
    depth: 5
branches:
    only:
      - master
language: node_js
node_js:
  - "6"
sudo: required
os:
  - linux
  - osx
osx_image: xcode8.2
dist: trusty
compiler:
  - clang
  - gcc
addons:
    apt:
        packages:
          - python
          - python-dev
          - python3
          - python3-dev

install:
  - cd libwally-core && ./tools/cleanup.sh && ./tools/autogen.sh
  - ./configure && make
  - cd src/swig_js
  - python makewrappers/wrap.py
  - cd ..
  - cd swig_js
  - npm i -g node-gyp
  - LIBWALLY_DIR=../.. npm i
  - npm i tape

before_install:
  - git clone https://github.com/jkozera/libwally-core.git -b wip_js
  - ./libwally-core/tools/travis_install.sh

script:
  - node test/test_hash.js

notifications:
    email: false
